### PR TITLE
Fix event reurn type

### PR DESCRIPTION
**Pull request by hcfw007**
## Checklist

- [x] Commit Messages follow the [Conventional Commits](https://conventionalcommits.org/) pattern
  - A feature commit message is prefixed "feat:"
  - A bugfix commit message is prefixed "fix:"
- [x] Tests for the changes have been added
- [x] CI has been passed. (GitHub actions all turns green)
- [x] CLA has been signed

## Description

>  Event Return Type Problem in #2384

### CODE REVIEW

**Comment by huan** [comment]
Please make sure the following requirements have been met for your PR before we can continue reviewing it:

2. The PR has passed all the CI tests and turns _green_. (you can execute all tests locally by running `npm test`)

**Comment by hcfw007** [comment]
> 3\. The PR has passed all the CI tests and turns _green_. (you can execute all tests locally by running `npm test`)

i'm working on that, however the failed test includes files that I did not change, so i'm being careful editing such files.

**Comment by hcfw007** [comment]
@huan OK everything should turn green now.
```ts
type AlterReturnType<Func extends Function, ReturnType> =
  Func extends (...args: infer Args) => any ? (...args: Args) => ReturnType : never
```
I tried to use a AlterReturnType to change the type of  `TypedEventEmitter<WechatyEventListeners>['on']`, however in this process, the type will lost the info of parameter extending WechatyEventListeners. So at last I use this type definition. It looks bad, but it will allow bot to chain `.on()` with `.start()`. 

Do you have any idea about how to change the return type of `TypedEventEmitter<WechatyEventListeners>['on']` without losing the parameter info?

**Comment by hcfw007** [comment]
@huan ping

**Review by huan — APPROVED** [review]
This fix is brilliant, thank you very much for this great improvement!

**Pull request merged**
