### PR TITLE
added hot load bots

### PR DESCRIPTION
**Pull request by Gcaufy**
It's really useful for development.

### CODE REVIEW

**Comment by zixia** [comment]
It's a very useful and cool example for #134 , Thanks!

**Comment by zixia** [comment]
Hi @Gcaufy ,

Thank you again for the great code example for the hot reload event listeners in Wechaty.

I would very much like to invite you to write a blog post for your code example in Wechaty Blog, for introducing your new example.

If you can write it, I will really appreciate because that could help others a lot.

Thanks!

**Comment by lijiarui** [comment]
Waiting for your PR on wechaty blog ~ @Gcaufy

**Comment by Gcaufy** [comment]
That's a big honor for me, Wechaty is a great solution, I believe there would be much more users recognize it. I'm using it currently, it's quite helpful. And absolutely I will recommend it to my friends.

For the blog, I'm glad to do it. I will do it when I'm free. :0)

**Comment by zixia** [comment]
Awesome.

Looking forward for your blog post then! :)

**Pull request merged**
