### PR TITLE
fix: typo in wechaty.ts

### PR DESCRIPTION
**Pull request by windmemory**
## I'm submitting a...

```
[ ] Bug Fix
[ ] Feature
[x] Other (Refactoring, Added tests, Documentation, ...)
```

## Checklist

- [x] Commit Messages follow the [Conventional Commits](https://conventionalcommits.org/) pattern
  - A feature commit message is prefixed "feat:"
  - A bugfix commit message is prefixed "fix:"
- [x] Tests for the changes have been added

## Description

Fix typo in `wechaty.ts` file.

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by huan** [comment]
Good catch! I believe you have some magic tools which helps you to find those typos!

**Comment by windmemory** [comment]
@huan Check [this](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)

**Comment by huan** [comment]
Thanks for sharing this great Code Spell Checker, installed!

**Comment by Gcaufy** [comment]
Cool,  definitely I need one. thx.
Find a spelling checker and installed, and seems working well.
https://github.com/kamykn/spelunker.vim

**Pull request merged**
