### PR TITLE
Add room member

### PR DESCRIPTION
**Pull request by su-chang**
## Checklist

- [ ] Commit Messages follow the [Conventional Commits](https://conventionalcommits.org/) pattern
  - A feature commit message is prefixed "feat:"
  - A bugfix commit message is prefixed "fix:"
- [ ] Tests for the changes have been added
- [ ] CI has been passed. (GitHub actions all turns green)
- [ ] SLA has been signed

## Description

> please describe the changes that you are making, with the related issue number.

### CODE REVIEW

**Comment by su-chang** [comment]
Related issue: https://github.com/wechaty/wechaty/issues/2142

**Review by windmemory — APPROVED** [review]

**Review by huan — APPROVED** [review]
LGTM

**Comment by huan** [comment]
Thank you very much for adding this improvement, appreciate it!

**Comment by huan** [comment]
BTW: Please remember to create another PR to update the master branch, or you will lost this feature in our next `@latest` npm package.

**Comment by su-chang** [comment]
Thank you for your mention.

**Comment by su-chang** [comment]
BTW: it seems that the new version `0.57.18` has not published success.

Error detail:
```shell
npm WARN exec The following package was not found and will be installed: version-exists
(node:12289) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
(Use `node --trace-deprecation ...` to show where the warning was created)

    Version 0.57.18 of the module wechaty does not exist!

npm ERR! code ERR_INVALID_ARG_TYPE
npm ERR! The "path" argument must be of type string. Received undefined
```

**Comment by huan** [comment]
Yes, I noticed this issue from yesterday.

All NPM publish keep failing and I have not found the reason yet.

Please let me know if you found anything related.

**Pull request merged**
