### PR TITLE
enhance #155 fire `room-join` when someone joins from a QR Code

### PR DESCRIPTION
**Pull request by lijiarui**
#155

### CODE REVIEW

**Comment by lijiarui** [comment]
done

and add `.` in `regexConfig.roomJoinQrcode `

**Comment by zixia** [comment]
It seems your test is failed:

```shell
  × src » puppet-web » firer » parseRoomJoin() Error: checkRoomJoin() not found matched re of "桔小秘" joined the group chat via your shared QR Code.
```

**Comment by lijiarui** [comment]
It seems fix...

**Comment by zixia** [comment]
LGTM

@dcsan this PR is related to your issue #155, could please confirm that  it provide the feature you want?

**Comment by lijiarui** [comment]
Please choose this one, it can identify the `inviter` in a right way.

**Comment by zixia** [comment]
@dcsan could you have a look on this PR? :)

**Comment by dcsan** [comment]
yep I will... by friday

**Comment by zixia** [comment]
https://github.com/wechaty/wechaty/issues/155#issuecomment-269919518

@dcsan Thanks for your review & test.

**Pull request merged**
