### PR TITLE
Add reason for logout event

### PR DESCRIPTION
**Pull request by su-chang**
## I'm submitting a...

```
[ ] Bug Fix
[x] Feature
[ ] Other (Refactoring, Added tests, Documentation, ...)
```

## Checklist

- [ ] Commit Messages follow the [Conventional Commits](https://conventionalcommits.org/) pattern
  - A feature commit message is prefixed "feat:"
  - A bugfix commit message is prefixed "fix:"
- [ ] Tests for the changes have been added

## Description

_please describe the changes that you are making_

_for features, please describe how to use the new feature_

_please include a reference to an existing issue, if applicable_

## Does this PR introduce a breaking change?

```
[ ] Yes
[ ] No
```

### CODE REVIEW

**Comment by su-chang** [comment]
Related issue: https://github.com/wechaty/wechaty-puppet-padplus/issues/100

**Comment by su-chang** [comment]
I think optional is flexible, if puppet which do not support the logout reason, it could ignore the parameter `reason`.

**Comment by windmemory** [comment]
If no reason, an empty string could also work. But optional also works. I will not insist on this point.

But I would insist on the separation of `login` and `logout` event since there is no reason for login event right now.

**Comment by su-chang** [comment]
Got it.

**Comment by huan** [comment]
@windmemory We should not approve any PR that did not pass the CI. If the CI is not green, we should never approve it unless we have to. Thanks!

**Comment by su-chang** [comment]
@huan ping

**Comment by huan** [comment]
Thanks for making the CI green for this PR.

**Pull request merged**
