### PR TITLE
get room owner on event 'room-join','room-topic'

### PR DESCRIPTION
**Pull request by JasLin**
issue 1: 

wxwebApp had hide uin of room members from some routing. so we can't get owner by using uin anymore: 

```javascript
memberList = memberList.filter(m => m.get('uin') === ownerUin)
     if (memberList.length > 0) {
       return memberList[0]
     } else {
       return null
     }
```

but on 'room-join' and 'room-topic' event ,we got a ``ChatRoomOwner```  property from rawObj, it can be used to load owner..
 
```javascript
rawObj:
   { Alias: '',
     AppAccountFlag: 0,
     AttrStatus: 0,
     ChatRoomId: 0,
     ChatRoomOwner: '@b261a88d4de1479cdf735c851fe22afe',
     City: '',
     ContactFlag: 2,
     DisplayName: '',
     EncryChatRoomId: '@dfee772e7d01ad0cfcdc5e2e8c81e558',
     HeadImgUpdateFlag: 1,
     HeadImgUrl: '/cgi-bin/mmwebwx-bin/webwxgetheadimg?seq=0&username=@@72317905edc07327e00aa61f690de1ea2a98117aca6ff32ddfe4eb0&skey=@crypt_9d729d2b_71e57bdd5f75
90fee74da393476f8160',
     HideInputBarFlag: 0,
     KeyWord: '',
     MMFromBatchGet: true,
     MMFromBatchget: true,
     MMInChatroom: true,
...
````

### CODE REVIEW

**Comment by JasLin** [comment]
i hate whitespace...

**Comment by JasLin** [comment]
@zixia  can not find thoese new modules?

https://travis-ci.org/wechaty/wechaty/jobs/178773741#L362
```
example/voice-to-text-bot.ts(13,31): error TS2307: Cannot find module 'request'.
example/voice-to-text-bot.ts(14,31): error TS2307: Cannot find module 'fluent-ffmpeg'.
```

**Comment by JasLin** [comment]
issues 2: throw new Error('no user')

when i trying to use https://app.wechaty.io. 

### reproduce

1. start robot 
2. and then opening wechaty.io
3. login 
4. robot got error 

```javascript
/home/jas/projects/learning/wechat/wechaty-ts/src/wechaty.ts:127
      throw new Error('no user')
            ^
Error: no user
    at Wechaty.user (/home/jas/projects/learning/wechat/wechaty-ts/src/wechaty.ts:127:13)
    at WebSocket.ws.on.e (/home/jas/projects/learning/wechat/wechaty-ts/src/io.ts:221:45)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at Receiver.ontext (/home/jas/projects/learning/wechat/wechaty-ts/node_modules/ws/lib/WebSocket.js:841:10)
    at /home/jas/projects/learning/wechat/wechaty-ts/node_modules/ws/lib/Receiver.js:536:18
    at /home/jas/projects/learning/wechat/wechaty-ts/node_modules/ws/lib/Receiver.js:368:7
    at /home/jas/projects/learning/wechat/wechaty-ts/node_modules/ws/lib/PerMessageDeflate.js:249:5
    at afterWrite (_stream_writable.js:387:3)
    at onwrite (_stream_writable.js:378:7)
```

i trace the code . when login in web , it will send a ws event 'update' to robot. and it will check call ```wechaty.user()``` , at the same time ,because your haven't login ,the ```wechaty.user()``` will throw errors. 

i change it to ```wechaty.puppet.user``` directly . then everything is ok.

https://github.com/wechaty/wechaty/pull/105/commits/c222fa18796395cf505ca357c37b26c1b8750f09

**Comment by zixia** [comment]
Great hack for the `ChatRoomOwner` property, thanks!

I'll check the new module requirement problem in the package.json, it's my bad.

BTW: app.wechaty.io use a very early stage ws protocol to communicate with Wechaty Runtime, so there's expected others' problem as well, please be careful when you use it.

**Comment by zixia** [comment]
CI failed becasue I forgot to run `npm install @types/request @types/fluent-ffmpeg --save-dev`. fixed.

**Pull request merged**
