### PR TITLE
feat: 🎸 message reply

### PR DESCRIPTION
**Pull request by hcfw007**
### <samp>🤖 Generated by Copilot at c398075</samp>

Added a `reply` method to `MessageMixin` to support replying to messages. The method uses the `wechaty-puppet` `Post` type to create and send the reply.
​

### <samp>🤖 Generated by Copilot at c398075</samp>

> _Sing, O Muse, of the skillful `MessageMixin`,_
> _That grants the power of reply to the swift messages,_
> _As they fly through the air like winged arrows of Apollo,_
> _Or like Hermes, who bears the golden staff of `Post`._

### <samp>🤖 Generated by Copilot at c398075</samp>

*  Import `Post` type from `wechaty-puppet` to use for replying messages ([link](https://github.com/wechaty/wechaty/pull/2534/files?diff=unified&w=0#diff-e1f2be6d124987fdd8237939cb04e6bb66e616e2edd7993e2ec9ccd07948c5aeR75))
*  Add `reply` method to `MessageMixin` class to allow a message to reply to another message with various content types ([link](https://github.com/wechaty/wechaty/pull/2534/files?diff=unified&w=0#diff-e1f2be6d124987fdd8237939cb04e6bb66e616e2edd7993e2ec9ccd07948c5aeR1087-R1107))

https://github.com/wechaty/wechaty/issues/2387

syntactic sugar for
```ts
wechaty.on('message', async msg => {
	const messagePost = msg.toPost()
	const post = bot.Post.builder()
	post.add('This is reply msg')
	post.reply(messagePost)
	post.type(PostType.Message)
	message.say(await post.build())
})
```

### CODE REVIEW

**Comment by huan** [comment]
copilot:all

**Comment by huan** [comment]
### WHAT
copilot:summary
​
copilot:poem

### WHY


### HOW
copilot:walkthrough

**Comment by huan** [comment]
copilot:summary

**Comment by huan** [comment]
I found a design mismatch in the `Message.reply()` and `Post.reply()`:

## Problem

Let's say:

1. the _Parent_ is the post/message we are replying to
2. the _Child_ is the reply we created as the response
 
### `Post.reply`

In `post.reply(arg)`:

1. the `post` is _Child_
1. the `arg` is _Parent_

```typescript
wechaty.on('message', async msg => {
	const messagePost = msg.toPost()
	const post = bot.Post.builder()
	post.add('This is reply msg')
	post.reply(messagePost)
	post.type(PostType.Message)
	message.say(await post.build())
})
```

### `Message.reply`

In `message.reply(arg)`:

1. the `message` is _Parent_
2. the `arg` is _Cihld_

```typescript
wechaty.on('message', async msg => {
	await message.reply('This is a reply msg')
})
```

## Solution

They should be the same semantics when calling `reply()`; we must change one to align with the other.

Can we answer the following question first, and find 3-5 developers to collect their answers, so that we can make the final decision:

1. `message.reply(arg)`: who is reply to who?
    1. `message` reply to `arg`
    2. `arg` reply to `message`
1. `post.reply(arg)`: who is reply to who?
    1. `post` reply to `arg`
    2. `arg` reply to `post`

For the first question, I think the only choice is 2: `arg` reply to `message` because the `arg` is a `Sayable` and has no `reply()` method.

So the final design should change the `Post.reply` design to use `arg` to reply to the `post`.

## Conslusion

### Before (the wrong design)

| | Parent | Child |
| :---: | :---: | :---: |
| message.reply(argSayable) | message | argSayable |
| post.reply(argPost) | argPost | post |

### After (the correct design)

| | Parent | Child |
| :---: | :---: | :---: |
| message.reply(argSayable) | message | argSayable |
| post.reply(argPost) | post | argPost |

**Comment by huan** [comment]
Any comments?

It would be great if you can send a PR to modify this because you can make sure every API is correct.

Or I will do it later next week.

Thanks!

**Comment by hcfw007** [comment]
> Any comments?
> 
> It would be great if you can send a PR to modify this because you can make sure every API is correct.
> 
> Or I will do it later next week.
> 
> Thanks!

In my oppinion, ```originalMessage.reply(args)``` means to send a new message with ```args``` replying to the originalMessage.

Because the originalMessage here is the instance of message representing an actual message in the IM.

```postBuilder.reply(args)``` mens set the post to reply to the ```args```.

The post builder here is the builder intance inside wechaty creating a new message.

**Comment by huan** [comment]
I can not understand. Can you explain more in details?

**Comment by hcfw007** [comment]
In my mind, the scenario is this:
```ts
bot.on('message', async (message) => {
  await message.reply('replied message')
})
```

So when I call ```reply``` on a message instance, I was actually replyting to the message, thus I want to quote the original message with the new messages in ```args```. The object I am handling is the original message.

When building a post with ```PostBuilder```, the object I am handling is the new post. So I want the new message to quote the message in the ```args```.

```ts
const builder = bot.Post.builder()
builder.add('some message')
builder.reply(message)
const post = await builder.build()
```

**Pull request closed without merging**
