### PR TITLE
Friendship contact

### PR DESCRIPTION
**Pull request by su-chang**
## I'm submitting a...

```
[x] Bug Fix
[ ] Feature
[ ] Other (Refactoring, Added tests, Documentation, ...)
```

## Checklist

- [ ] Commit Messages follow the [Conventional Commits](https://conventionalcommits.org/) pattern
  - A feature commit message is prefixed "feat:"
  - A bugfix commit message is prefixed "fix:"
- [ ] Tests for the changes have been added

## Description

_please describe the changes that you are making_

_for features, please describe how to use the new feature_

_please include a reference to an existing issue, if applicable_

## Does this PR introduce a breaking change?

```
[ ] Yes
[ ] No
```

### CODE REVIEW

**Comment by su-chang** [comment]
Related issue: https://github.com/wechaty/wechaty/issues/1954

**Comment by huan** [comment]
Thanks for the PR!

I have a question: it seems the `ready()` in `contact()` method is not necessary for puppets other than Donut, did you know the reason for that?

BTW: this is a breaking change, I'd like to find the fundamental reason for this problem, and I hope we can fix it without any breaking change.

**Comment by su-chang** [comment]
> I have a question: it seems the `ready()` in `contact()` method is not necessary for puppets other than Donut, did you know the reason for that?

I do not know about that. Could you please explain it for me?

> BTW: this is a breaking change, I'd like to find the fundamental reason for this problem, and I hope we can fix it without any breaking change.

Yeah, it is a breaking change, but I think it is better for user to get contact payload rather than an empty Contact object.

**Comment by huan** [comment]
Instead of introducing a breaking change, I'd like to move `ready()` inside to archive the same goal.

Please see my latest changes in your PR, and let me know what you think.

**Comment by su-chang** [comment]
Understand, it's a better way than what I did! 

Thank you very much.

Cheers!

**Pull request merged**
