### PR TITLE
Conversation read

### PR DESCRIPTION
**Pull request by su-chang**
## Checklist

- [ ] Commit Messages follow the [Conventional Commits](https://conventionalcommits.org/) pattern
  - A feature commit message is prefixed "feat:"
  - A bugfix commit message is prefixed "fix:"
- [ ] Tests for the changes have been added
- [ ] CI has been passed. (GitHub actions all turns green)
- [ ] SLA has been signed

## Description

> please describe the changes that you are making, with the related issue number.

### CODE REVIEW

**Review by windmemory — APPROVED** [review]
Looks good to me, approved!

**Review by huan — COMMENTED** [review]
After reading the example code, it seems that the `contact.read()` is not intuition enough...

I'm thinking about a better for the `read` ... 

Could you please provide some alternative choices for this name? thank you very much!

**Comment by su-chang** [comment]
Maybe due to the concept of tense is not obvious, make `read` ambiguity.

**alternative choices**
- [ ] hasRead
- [ ] markRead
- [ ] ignore
- [ ] overlook

**Review by huan — CHANGES_REQUESTED** [review]
Please send this PR to the master branch instead of `v0.57` because we are moving forward with the `master` branch.

**Review by huan — CHANGES_REQUESTED** [review]
Please follow my review to update the API, thanks.

**Comment by su-chang** [comment]
Thank you for your review, I will push a new PR replace this one. This PR close now.

**Pull request closed without merging**
